### ISSUE TITLE
@aurelia/ts-jest and @aurelia/babel-jest need to update to support Jest v27

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1175]
# 🐛 Bug Report

Our jest integration doesn't work on latest Jest v27.

## 🤔 Expected Behavior

It should work.

## 😯 Current Behavior

Jest v27 switched to ESM format.
```
> jest

TypeError: Jest: a transform must export something.
    at /Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:386:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async ScriptTransformer.loadTransformers (/Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:378:5)
    at async createScriptTransformer (/Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:1106:3)
    at async /Users/huocp/playground/my-app/node_modules/@jest/core/build/TestScheduler.js:269:31
    at async Promise.all (index 0)
    at async TestScheduler.scheduleTests (/Users/huocp/playground/my-app/node_modules/@jest/core/build/TestScheduler.js:262:5)
    at async runJest (/Users/huocp/playground/my-app/node_modules/@jest/core/build/runJest.js:387:19)
    at async _run10000 (/Users/huocp/playground/my-app/node_modules/@jest/core/build/cli/index.js:408:7)
```
## 💁 Possible Solution

Upgrade @aurelia/ts-jest and @aurelia/babel-jest to latest Jest APIs.

## 🌍 Your Environment
Not applicable

**Comment by 3cp** [comment]
There is something not wrong in monorepo setup.
Currently our jest plugins all have the same version number as any other packages in this monorepo, 2.0.0-alpha.5.
But we need a breaking change in @aurelia/ts-jest and @aurelia/babel-jest to support jest v27.
How to handle that in this monorepo?
Monorepo really doesn't make much sense in version control, as every individual packages have their own breaking changes. It also doesn't make any sense to force all packages to bump version number even when only one or two of the packages got real code change.

**Comment by bigopon** [comment]
In the future, we may need to split tooling packages, which are much more prone to breaking changes for dependency chain reasons. For now, I think we can afford to go through many alpha versions as needed to have a predictable version across all packages.

**Comment by 3cp** [comment]
The jest v27 has some API changes. Over the years, I am really tired of all these breaking changes. Nodejs, webpack, jest, karma, cypress, babel, typescript, eslint... Counting the days until Deno (with built-in linter/tester/bundler/formatter) rules us all...
