### ISSUE TITLE
Build failed with valueConverter/bindingBehavior by convention

### ISSUE THREAD

**Issue by aegenet** [aurelia/aurelia#1442]
# 🐛 Bug Report

Since Aurelia 2.0.0-alpha.30, if you add a `valueConverter` or a `bindingBehavior` by convention, your build will fail.

## 🤔 Expected Behavior

Build without error.

## 😯 Current Behavior

An error occurred, with the following message:

```bash
Error: [tsl] ERROR in C:\dev2022\au2-issue-value-converter\src\converters\json-stringify.ts(2,10)
      TS2305: Module '"@aurelia/runtime-html"' has no exported member 'valueConverter'.
    at makeError (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:93:19)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:63:27
    at Array.map (<anonymous>)
    at formatErrors (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:46:14)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:153:66
    at Array.forEach (<anonymous>)
    at provideErrorsToWebpack (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:150:31)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:36:9
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\instances.js:203:13
    at fn (C:\dev2022\au2-issue-value-converter\node_modules\webpack\lib\Compilation.js:478:10)
 @ ./src/main.ts 2:0-74 5:14-41
```

```bash
Error: [tsl] ERROR in C:\dev2022\au2-issue-value-converter\src\binding-behavior\log.ts(2,10)
      TS2305: Module '"@aurelia/runtime-html"' has no exported member 'bindingBehavior'.
    at makeError (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:93:19)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:63:27
    at Array.map (<anonymous>)
    at formatErrors (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\utils.js:46:14)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:153:66
    at Array.forEach (<anonymous>)
    at provideErrorsToWebpack (C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:150:31)
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\after-compile.js:36:9
    at C:\dev2022\au2-issue-value-converter\node_modules\ts-loader\dist\instances.js:203:13
    at fn (C:\dev2022\au2-issue-value-converter\node_modules\webpack\lib\Compilation.js:478:10)
 @ ./src/main.ts 3:0-60 6:43-61
```

## 💁 Possible Solution

You can specify your `valueConverter` explicitly:

```diff
+ import { valueConverter } from 'aurelia';
/**
 * JSON Stringify
 */
+ @valueConverter('jsonStringify')
export class JsonStringifyValueConverter {
  toView(value: unknown, space = 2) {
    return JSON.stringify(value, undefined, space);
  }
}

```

This issue is due to recent changes in aurelia exports:
`valueConverter` and `bindingBehavior` are no longer exported by `@aurelia/runtime-html` (but by `@aurelia/runtime`).

## 🔦 Context

Use conventions.

## 💻 Code Sample

**Repository**: https://github.com/aegenet/au2-issue-value-converter

```bash
git clone git@github.com:aegenet/au2-issue-value-converter.git
cd ./au2-issue-value-converter
yarn
yarn build -- --stats verbose
```

Or manually:

```bash
# Aurelia 2 skeleton (typescript, webpack)
npx makes aurelia

# Add a value converter by convention (XxxxValueConverter) or a binding behavior (XxxxBindingBehavior).

# build
yarn build
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |  >= 2.0.0-alpha.30 (2.0.0-alpha.30 to 2.0.0-alpha.33)
| Language         | TypeScript
| Browser          | Chrome/Firefox
| Bundler          | Webpack
| Operating System | Windows 11
| NPM/Node/Yarn    | Yarn 1.22.18

**Comment by bigopon** [comment]
Some barrel reexports have been cut to make it simple, one-way-to-do-things. This probably can go back to the runtime-html

**Comment by bigopon** [comment]
this is fixed in alpha 34 https://github.com/aurelia/aurelia/blob/master/docs/CHANGELOG.md#200-alpha34-2022-06-03

Thanks @aegenet
