### ISSUE TITLE
Setting a repeat bound array causes an exception

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1720]
# 🐛 Bug Report

Setting a repeat bound array causes an exception

Repro link https://gist.dumber.app/?gist=8df7cd9836ebda063ad4a37650ceb2c0

## 🤔 Expected Behavior

No exception... I guess :)

## 😯 Current Behavior

Exception :)

AUR0814: viewsLen=6, mapLen=5
    at createError (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:309:34)
    at mismatchedLengthError (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:9207:57)
    at Repeat._createAndActivateAndSortViewsByKey (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:9074:19)
    at Repeat._applyIndexMap (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:8947:22)
    at Repeat.itemsChanged (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:8765:14)
    at BindableObserver.setValue (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:568:29)
    at PropertyBinding.updateTarget (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:1956:30)
    at PropertyBinding.handleChange (webpack-internal:///../../node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs:1979:18)
    at SubscriberRecord.notify (webpack-internal:///../../node_modules/@aurelia/runtime/dist/esm/index.mjs:1521:32)
    at SetterObserver.setValue (webpack-internal:///../../node_modules/@aurelia/runtime/dist/esm/index.mjs:4294:23)

## 🔦 Context

This is a very critical bug

## 💻 Code Sample

https://gist.dumber.app/?gist=8df7cd9836ebda063ad4a37650ceb2c0

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | beta.3
| Language         | Typescript
| Browser          | Chrome
| Bundler          | webpack

**Comment by bigopon** [comment]
thanks @MaximBalaganskiy . This is because a premature optimization in the repeater key mode. It happens when there' duplicate values in the array.

cc @fkleuver
