### ISSUE TITLE
router-lite: unexpected state at endTransition 3 of VPA

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1789]
# 🐛 Bug Report

Changing `transitionPlan` to `replace` on parent route leads to the following exception when navigating to a child route:

```
AUR3352: Unexpected state at endTransition 3 of VPA(state:currDeactivate|nextLoadDone,plan:'replace',n:RN(ctx:'my-app/products/sub-child-detail',c:'SubChildDetail',path:'detail/:subid'),c:RN(ctx:'my-app/products/sub-child-init',c:'SubChildInit',path:''),viewport:VP(ctx:'my-app/products',name:'default'))
    at ViewportAgent._unexpectedState (https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:11078:15)
    at ViewportAgent._endTransition (https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:11058:26)
    at https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:11011:34
    at Array.forEach (<anonymous>)
    at ViewportAgent._endTransition (https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:11010:37)
    at https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:12123:38
    at Array.forEach (<anonymous>)
    at https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:12122:21
    at Batch._invoke (https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:9464:13)
    at Batch._pop (https://au2conventionskmtxcj-2nwf--9000--e809191e.local-credentialless.webcontainer.io/entry.bundle.js:9455:21)
```

Repro: https://stackblitz.com/edit/au2-conventions-kmtxcj

Thanks for checking that.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev version

**Comment by Sayan751** [comment]
@elitastic Thanks for reporting this issue. I am currently looking into this. Note that the things should properly work if you remove the `transitionPlan` configuration. The default logic should work correctly. There might be multiple solutions to this problem. The easiest of those will be to remove the option to set `replace` as `transitionPlan`, as the default logic can be considered as 'replace'. The only difference is that if the route parameters to the component are the same, it does not deactivate (and subsequently reactivate) the current component. May I ask, what is your use-case to set the `transitionPlan` explicitly to `replace`?
