### ISSUE TITLE
Errors about relative paths of imports within Aurelia's modules when trying to build after installing Dialogs

### ISSUE THREAD

**Issue by ShadowFiendZX** [aurelia/aurelia#1796]
| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | latest (as of 07/13/2023)
| Language         | TypeScript
| Browser          | Chrome
| Bundler          | WebPack
| Operating System | Windows
| NPM/Node/Yarn    | NPM

Hi all, I haven't used Node in almost a decade, and am really new to WebPack, Aurelia, etc, so forgive me if I'm making some sort of stupid beginner's mistake.

Essentially, I'm trying to use the default Aurelia skeleton to test implementing Dialogs.

When attempting to do so, I get several errors about being unable to locate various `.mjs` files, in relation to imports within aurelia.

This is rather vague, but the actual errors will come later on in this post, after I've detailed what I've done, in case I've made a mistake somewhere.

Aside from the various intro posts, what I followed was [App Configuration and Startup](https://aurelia.io/docs/fundamentals/app-configuration-and-startup),
[Dialogs](https://aurelia.io/docs/plugins/dialog), as well as the [noHtmlLoader section of this Wiki post about AureliaPlugin](https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options).

You can find a public repo with the test project [here](https://github.com/ShadowFiendZX/DialogTest).
Forgive the use of spaces instead of tabs, I was trying to keep the commit diffs minimal.

Here's the steps I followed :

- `npx makes aurelia DialogTest -s typescript`
I know the default TypeScript project is equivalent to `npx makes aurelia DialogTest -s typescript,jest`, but I didn't want to have to deal with jest, and the default app seemed
to run fine without jest.
- `cd DialogTest`
- `npm install`
- `npm run build` just to make sure it builds.

After that I made a commit, and made changes to get the html file to load when I double click it :

index.html
```diff
- <base href="/">
+ <base href=".">
```

Next I edited the scripts in `package.json` to my liking :

```diff
- "build": "rimraf dist && webpack --env production",
+ "build": "rimraf dist && webpack --env development",
+ "release": "rimraf dist && webpack --env production",
```

Next comes trying to use Dialogs :

Install the necessary packages : 

```
npm install aurelia-bootstrapper
npm install aurelia-dialog
npm install aurelia-webpack-plugin --save-dev
```

Edit webpack.config.js :

```diff
+ const { AureliaPlugin } = require('aurelia-webpack-plugin');

- devtool: production ? undefined : 'eval-cheap-source-map',
+ devtool: production ? 'source-map' : 'inline-source-map',

- entry: {
-      entry: './src/main.ts'
-    },

+ entry: {
+			// the 'aurelia-bootstrapper' entry point is responsible for resolving your app code
+			app: [ 'aurelia-bootstrapper' ]
+		},

- filename: production ? '[name].[contenthash].bundle.js' : '[name].bundle.js'
+ filename: '[name].js'

+      // the AureliaPlugin translates Aurelia's conventions to something Webpack understands
+      // and must be included in order for Webpack to work
+      new AureliaPlugin(),
```

Edit main.ts :

```diff
- import Aurelia from 'aurelia';
- import { MyApp } from './my-app';

- Aurelia
-  .app(MyApp)
-  .start();

+ import { Aurelia, PLATFORM } from 'aurelia-framework';

+ export async function configure(au : Aurelia)
+ {
+ 	au.use
+ 		.standardConfiguration()
+ 		.developmentLogging()
+ 		.plugin(PLATFORM.moduleName('aurelia-dialog'));

+ 	await au.start();
+ 	await au.setRoot(PLATFORM.moduleName('my-app')); // Note the PLATFORM.moduleName
}
```

Edit app.ts, ignoring the changes for implementing Prompt, which can be found in the linked repo :

```ts
import { autoinject } from 'aurelia-framework';
import { DialogCloseResult, DialogService } from 'aurelia-dialog';
import { Prompt } from './prompt'

@autoinject
export class MyApp
{
	public message = 'Hello World!';
	public inputBox : string;

	constructor(private dialogService : DialogService)
	{
	}

	buttonPress() : void
	{
		this.message = 'Success';

		this.dialogService.open({ 'viewModel' : Prompt, model : 'Please work', lock : true }).whenClosed((response : DialogCloseResult) =>
		{
			console.log(response.wasCancelled);
			console.log(response.output);
		});
	}
}
```

Edit index.html :

```diff
- <body>
-   <my-app></my-app>
+ <body aurelia-app="main">
```

At this point, running `npm run build` errors. I edited the `build` script to include `--stats-children --stats-error-details` as per the suggestions in the console :

```diff
- "build": "rimraf dist && webpack --env development",
+ "build": "rimraf dist && webpack --env development --stats-children --stats-error-details",
```

Here is the errored output :

<details>
<summary>Click to expand</summary>

```
$ npm run build

> DialogTest@0.1.0 build
> rimraf dist && webpack --env development

assets by path *.js 2.89 MiB
  asset entry.bundle.js 2.82 MiB [emitted] (name: entry)
  asset vendors-node_modules_aurelia-dialog_dist_native-modules_ux-dialog-renderer_js.bundle.js 27.8 KiB [emitted] (id hint: vendors)
  asset node_modules_aurelia-dialog_dist_native-modules_native-dialog-renderer_js.bundle.js 25.8 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_default-styles_js.bundle.js 7 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-footer_js.bundle.js 4.85 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-header_js.bundle.js 3.88 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_attach-focus_js.bundle.js 3 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-body_js.bundle.js 1.91 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog_js.bundle.js 1.8 KiB [emitted]
asset favicon.ico 14.7 KiB [emitted]
asset index.html 3.51 KiB [emitted]
runtime modules 7.54 KiB 13 modules
modules by path ./node_modules/ 1.01 MiB
  modules by path ./node_modules/aurelia-dialog/dist/native-modules/*.js 39.6 KiB 10 modules
  modules by path ./node_modules/style-loader/dist/runtime/*.js 5.84 KiB 6 modules
  modules by path ./node_modules/aurelia-webpack-plugin/runtime/*.js 2.17 KiB 2 modules
  modules by path ./node_modules/@aurelia/ 289 KiB 2 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 2.74 KiB 2 modules
  + 21 modules
modules by path ./src/ 12.4 KiB
  modules by path ./src/*.ts 9.14 KiB 3 modules
  modules by path ./src/*.html 1.36 KiB 2 modules
  modules by path ./src/*.css 1.89 KiB
    ./src/my-app.css 1.25 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/my-app.css 649 bytes [built] [code generated]

ERROR in ./node_modules/@aurelia/runtime-html/dist/native-modules/index.mjs 1:0-566
Module not found: Error: Can't resolve '../kernel/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'
 @ ./src/my-app.ts 3:0-54 22:4-17 27:0-90
 @ ./src/main.ts

ERROR in ./node_modules/@aurelia/runtime-html/dist/native-modules/index.mjs 3:0-89
Module not found: Error: Can't resolve '../metadata/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'
 @ ./src/my-app.ts 3:0-54 22:4-17 27:0-90
 @ ./src/main.ts

ERROR in ./node_modules/@aurelia/runtime-html/dist/native-modules/index.mjs 5:0-641
Module not found: Error: Can't resolve '../runtime/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'
 @ ./src/my-app.ts 3:0-54 22:4-17 27:0-90
 @ ./src/main.ts

ERROR in ./node_modules/@aurelia/runtime-html/dist/native-modules/index.mjs 7:0-90
Module not found: Error: Can't resolve '../platform-browser/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'
 @ ./src/my-app.ts 3:0-54 22:4-17 27:0-90
 @ ./src/main.ts

ERROR in ./node_modules/@aurelia/runtime-html/dist/native-modules/index.mjs 9:0-81
Module not found: Error: Can't resolve '../platform/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'
 @ ./src/my-app.ts 3:0-54 22:4-17 27:0-90
 @ ./src/main.ts

ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/aurelia-webpack-plugin/dist/html-requires-loader.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html>
  |
  ModuleParseError: Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/aurelia-webpack-plugin/dist/html-requires-loader.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html>
  |
      at handleParseError (D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:982:19)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:1101:5
      at processResult (D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:806:11)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:866:5
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:407:3
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:233:10)
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:240:10)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:255:3
      at runSyncOrAsync (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:143:11)
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:251:2)

  - NormalModule.js:982 handleParseError
    [DialogTest]/[webpack]/lib/NormalModule.js:982:19

  - NormalModule.js:1101
    [DialogTest]/[webpack]/lib/NormalModule.js:1101:5

  - NormalModule.js:806 processResult
    [DialogTest]/[webpack]/lib/NormalModule.js:806:11

  - NormalModule.js:866
    [DialogTest]/[webpack]/lib/NormalModule.js:866:5

  - LoaderRunner.js:407
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:407:3

  - LoaderRunner.js:233 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:233:10

  - LoaderRunner.js:240 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:240:10

  - LoaderRunner.js:255
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:255:3

  - LoaderRunner.js:143 runSyncOrAsync
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:143:11

  - LoaderRunner.js:251 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:251:2

  - child-compiler.js:169
    [DialogTest]/[html-webpack-plugin]/lib/child-compiler.js:169:18

  - Compiler.js:551 finalCallback
    [DialogTest]/[webpack]/lib/Compiler.js:551:5

  - Compiler.js:577
    [DialogTest]/[webpack]/lib/Compiler.js:577:11

  - Compiler.js:1200
    [DialogTest]/[webpack]/lib/Compiler.js:1200:17


  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [DialogTest]/[tapable]/lib/Hook.js:18:14

  - Compiler.js:1196
    [DialogTest]/[webpack]/lib/Compiler.js:1196:33

  - Compilation.js:2795 finalCallback
    [DialogTest]/[webpack]/lib/Compilation.js:2795:11

  - Compilation.js:3100
    [DialogTest]/[webpack]/lib/Compilation.js:3100:11




1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

5 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.1 compiled with 7 errors in 3636 ms
```

</details>

If you look at the errors, you'll see a few like this : `Module not found: Error: Can't resolve '../kernel/dist/native-modules/index.mjs' in 'D:\Misc_Projects\DialogTest\DialogTest\node_modules\@aurelia\runtime-html\dist\native-modules'`

I then went to the files that are erroring, and replaced all the errored imports to point to proper paths.
For example, here's one of several edits I made to `node_modules\@aurelia\runtime-html\dist\native-modules\index.mjs`

```diff
- import { Protocol as t, getPrototypeChain as e, kebabCase as i, noop as s, DI as n, Registration as r, firstDefined as l, mergeArrays as h, resolve as a, IPlatform as c, emptyArray as u, InstanceProvider as f, fromDefinitionOrDefault as d, pascalCase as m, fromAnnotationOrTypeOrDefault as g, fromAnnotationOrDefinitionOrTypeOrDefault as p, IContainer as v, optional as b, onResolveAll as x, onResolve as w, all as y, camelCase as k, IServiceLocator as C, emptyObject as A, ILogger as B, transient as S, toArray as _ } from "../kernel/dist/native-modules/index.mjs";
+ import { Protocol as t, getPrototypeChain as e, kebabCase as i, noop as s, DI as n, Registration as r, firstDefined as l, mergeArrays as h, resolve as a, IPlatform as c, emptyArray as u, InstanceProvider as f, fromDefinitionOrDefault as d, pascalCase as m, fromAnnotationOrTypeOrDefault as g, fromAnnotationOrDefinitionOrTypeOrDefault as p, IContainer as v, optional as b, onResolveAll as x, onResolve as w, all as y, camelCase as k, IServiceLocator as C, emptyObject as A, ILogger as B, transient as S, toArray as _ } from "../../../kernel/dist/native-modules/index.mjs";
```

Here's the list of all the files I had to edit :

```
node_modules\@aurelia\kernel\dist\native-modules\index.mjs
node_modules\@aurelia\platform-browser\dist\native-modules\index.mjs
node_modules\@aurelia\runtime-html\dist\native-modules\index.mjs
node_modules\@aurelia\runtime\dist\native-modules\index.mjs
```

After making the necessary changes to the relative paths, building still fails :

<details>
<summary>Click to expand</summary>

```
$ npm run build

> DialogTest@0.1.0 build
> rimraf dist && webpack --env development

assets by path *.js 3.35 MiB
  asset entry.bundle.js 3.28 MiB [emitted] (name: entry)
  asset vendors-node_modules_aurelia-dialog_dist_native-modules_ux-dialog-renderer_js.bundle.js 27.8 KiB [emitted] (id hint: vendors)
  asset node_modules_aurelia-dialog_dist_native-modules_native-dialog-renderer_js.bundle.js 25.8 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_default-styles_js.bundle.js 7 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-footer_js.bundle.js 4.85 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-header_js.bundle.js 3.88 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_attach-focus_js.bundle.js 3 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog-body_js.bundle.js 1.91 KiB [emitted]
  asset node_modules_aurelia-dialog_dist_native-modules_ux-dialog_js.bundle.js 1.8 KiB [emitted]
asset favicon.ico 14.7 KiB [emitted]
asset index.html 3.51 KiB [emitted]
runtime modules 7.54 KiB 13 modules
modules by path ./node_modules/ 1.19 MiB
  modules by path ./node_modules/aurelia-dialog/dist/native-modules/*.js 39.6 KiB 10 modules
  modules by path ./node_modules/@aurelia/ 472 KiB 6 modules
  modules by path ./node_modules/style-loader/dist/runtime/*.js 5.84 KiB 6 modules
  modules by path ./node_modules/aurelia-webpack-plugin/runtime/*.js 2.17 KiB 2 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 2.74 KiB 2 modules
  + 21 modules
modules by path ./src/ 12.4 KiB
  modules by path ./src/*.ts 9.14 KiB 3 modules
  modules by path ./src/*.html 1.36 KiB 2 modules
  modules by path ./src/*.css 1.89 KiB
    ./src/my-app.css 1.25 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/my-app.css 649 bytes [built] [code generated]

ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/aurelia-webpack-plugin/dist/html-requires-loader.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html>
  |
  ModuleParseError: Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/aurelia-webpack-plugin/dist/html-requires-loader.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html>
  |
      at handleParseError (D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:982:19)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:1101:5
      at processResult (D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:806:11)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\webpack\lib\NormalModule.js:866:5
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:407:3
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:233:10)
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:240:10)
      at D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:255:3
      at runSyncOrAsync (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:143:11)
      at iterateNormalLoaders (D:\Misc_Projects\DialogTest\DialogTest\node_modules\loader-runner\lib\LoaderRunner.js:251:2)

  - NormalModule.js:982 handleParseError
    [DialogTest]/[webpack]/lib/NormalModule.js:982:19

  - NormalModule.js:1101
    [DialogTest]/[webpack]/lib/NormalModule.js:1101:5

  - NormalModule.js:806 processResult
    [DialogTest]/[webpack]/lib/NormalModule.js:806:11

  - NormalModule.js:866
    [DialogTest]/[webpack]/lib/NormalModule.js:866:5

  - LoaderRunner.js:407
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:407:3

  - LoaderRunner.js:233 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:233:10

  - LoaderRunner.js:240 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:240:10

  - LoaderRunner.js:255
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:255:3

  - LoaderRunner.js:143 runSyncOrAsync
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:143:11

  - LoaderRunner.js:251 iterateNormalLoaders
    [DialogTest]/[loader-runner]/lib/LoaderRunner.js:251:2

  - child-compiler.js:169
    [DialogTest]/[html-webpack-plugin]/lib/child-compiler.js:169:18

  - Compiler.js:551 finalCallback
    [DialogTest]/[webpack]/lib/Compiler.js:551:5

  - Compiler.js:577
    [DialogTest]/[webpack]/lib/Compiler.js:577:11

  - Compiler.js:1200
    [DialogTest]/[webpack]/lib/Compiler.js:1200:17


  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [DialogTest]/[tapable]/lib/Hook.js:18:14

  - Compiler.js:1196
    [DialogTest]/[webpack]/lib/Compiler.js:1196:33

  - Compilation.js:2795 finalCallback
    [DialogTest]/[webpack]/lib/Compilation.js:2795:11

  - Compilation.js:3100
    [DialogTest]/[webpack]/lib/Compilation.js:3100:11




1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.88.1 compiled with 2 errors in 3576 ms
```

</details>

This error isn't necessarily related to Dialogs, but it still prevents the build.
This is where the [noHtmlLoader section of this Wiki post about AureliaPlugin](https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options) comes in.

It states this :

```
If you use HtmlWebpackPlugin, which creates static html files to load your app, you should note that this adds a loader for all .html files.
It means that if you specify a template like new HtmlWebpackPlugin({ template: 'index.html' }), it will prevent the fallback ejs loader to kick in (see HtmlWebpackPlugin docs). There are several workarounds:

use a different file extension like index.ejs.
```

It lists a few more options, but I tried that one first.

This just requires renaming `index.html` to `index.ejs`, and the following change in `webpack.config.js` :

```diff
- new HtmlWebpackPlugin({ template: 'index.html', favicon: 'favicon.ico' }),
+ new HtmlWebpackPlugin({ template: 'index.ejs', favicon: 'favicon.ico' }),
```

With those final changes, the build will succeed, the webpage will load, and the dialog will work.

That final step took a lot of digging to find. Although this issue isn't about needing to choose one of a few solutions to fixing the html loader issue, it'd be nice if the main tutorials mentioned it.
Unless it does, and I missed it.

**Comment by Vheissu** [comment]
The problem here is you're mixing Aurelia 2 and Aurelia 1 dependencies. Those dependencies you're installing are not for Aurelia 2. Do you want to use Aurelia 1 or Aurelia 2?

Dialogs for v2 are documented here: https://docs.aurelia.io/aurelia-packages/dialog

**Comment by ShadowFiendZX** [comment]
I want to use Aurelia 2. I'm not sure when I might've ended up on the Aurelia 1 docs, since I definitely remember reading through the quite a lot of the Aurelia 2 docs before I started experimenting with code.

Thanks for pointing that out where I went wrong.

**Comment by Vheissu** [comment]
@ShadowFiendZX No problem. It is admittedly an easy mistake to make as Aurelia 2 docs refer mostly to Aurelia in a generic sense, not Aurelia 2, so you could get confused. If you get stuck, reach out on Discord! https://discord.gg/766GHV2GJb
