### ISSUE TITLE
Fresh install with parcel and yarn not working

### ISSUE THREAD

**Issue by Stopi** [aurelia/aurelia#1811]
# 🐛 Bug Report

When generating a new custom project following the documentation, I receive error message.

Then when running the server, if I update the code (js, html or css) nothing is refreshed in the browser.
Even killing the parcel server & restarting it doesn't work, old version of the website seems cached.

## 🤔 Expected Behavior

I expect a fresh project to run just as it should.
Documentation doesn't really give alternatives as for how to build a project except than following that `npx makes` wizard.

## 😯 Current Behavior

I don't see any error in the terminal, it just doesn't seem to react to file changes.

## 🔦 Context

```bash
$ yarn add aurelia makes
yarn add v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

warning No license field
success Saved 2 new dependencies.
info Direct dependencies
├─ aurelia@2.0.0-beta.8
└─ makes@3.2.0
info All dependencies
├─ aurelia@2.0.0-beta.8
└─ makes@3.2.0
Done in 3.80s.


$ npx makes aurelia
makes v3.2.0 https://makes.js.org
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/HEAD

         #
      ######   xxx
     ########  xxxx   ####         _                  _ _         ____
   x   ########    ########       / \  _   _ _ __ ___| (_) __ _  |___ \
     x  ######  #############    / _ \| | | | '__/ _ \ | |/ _` |   __) |
  xxxxx  ##  ###############    / ___ \ |_| | | |  __/ | | (_| |  / __/
   xxxxx  ###############      /_/   \_\__,_|_|  \___|_|_|\__,_| |_____|
    x ###############  xxx
    ##############  #   xx
 ##############  ######          https://aurelia.io
  ########## x  ########         https://github.com/aurelia
    #####  xxxx   ########       https://twitter.com/aureliaeffect
     #   x  x      ######
                     #

✔ Please name this new project: › test
✔ Would you like to use the default setup or customize your choices? › Custom Aurelia 2 Project
✔ What kind of Aurelia 2 project? › Application
✔ What Aurelia 2 release would you like to use? › Latest
✔ Which bundler would you like to use? › Parcel
✔ What transpiler would you like to use? › Babel
✔ Do you want to use Shadow DOM or CSS Module? › Use Shadow DOM
✔ What CSS preprocessor to use? › Plain CSS
✔ What unit testing framework to use? › Jasmine
✔ Do you want to setup e2e test? › Yes (Playwright)
✔ What kind of sample code do you want in this project? › Bare minimum
[makes] Project test has been created.
✔ Do you want to install npm dependencies now? › Yes, use yarn (node-modules)
yarn install v1.22.19
warning ../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
warning parcel > @parcel/config-default > @parcel/optimizer-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 99.03s.
yarn run v1.22.19
warning ../package.json: No license field
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: yarn exit code: 1
    at ChildProcess.<anonymous> (/home/www/test/client/node_modules/makes/dist/index.js:1:25653)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)


$ npm start

> test@0.1.0 start
> parcel -p 9000

Server running at http://localhost:9000
✨ Built in 2.08s
```
## 🌍 Your Environment

```bash
$ uname -a 
Linux stopi 5.15.11-gentoo #1 SMP Wed Jan 12 09:54:56 +07 2022 x86_64 Intel(R) Core(TM) i5 CPU 650 @ 3.20GHz GenuineIntel GNU/Linux
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.8 |
| Language         | Javascript |
| Browser          | Firefox |
| Bundler          | Parcel - 2.9.3 |
| Operating System | Linux amd64 (Gentoo) |
| NPM/Node/Yarn    | v18.16.0 |

**Comment by Stopi** [comment]
It seems building the same project with Babel instead of Parcel gives me the same error message:
```bash
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: yarn exit code: 1
    at ChildProcess.<anonymous> (/home/www/test/node_modules/makes/dist/index.js:1:25653)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
But at least when changing my-app's source, the changes are showing in the browser.

**Comment by Stopi** [comment]
Today I tried again on a different host with nodejs v20.2.0, that seem to fix the "refreshing" issue with parcel.
But I still get the "dlx" error message when creating the project.

**Comment by Stopi** [comment]
I went back to this after a while and I realized the error message was because of yarn's version.

There are several stable versions of yarn and the "dlx" command is a recent one.
So since I was using v1.22.19, it couldn't work.
```
$ yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/4.0.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.0.2.cjs
➤ YN0000: Done in 2s 358ms

$ rm package.json
# this is required for the npx command to run

$ yarn --version
4.0.2

$ npx makes aurelia
makes v3.2.0 https://makes.js.org
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/HEAD

         #
      ######   xxx
     ########  xxxx   ####         _                  _ _         ____
   x   ########    ########       / \  _   _ _ __ ___| (_) __ _  |___ \
     x  ######  #############    / _ \| | | | '__/ _ \ | |/ _` |   __) |
  xxxxx  ##  ###############    / ___ \ |_| | | |  __/ | | (_| |  / __/
   xxxxx  ###############      /_/   \_\__,_|_|  \___|_|_|\__,_| |_____|
    x ###############  xxx
    ##############  #   xx
 ##############  ######          https://aurelia.io
  ########## x  ########         https://github.com/aurelia
    #####  xxxx   ########       https://twitter.com/aureliaeffect
     #   x  x      ######
                     #

✔ Please name this new project: › test
✔ Would you like to use the default setup or customize your choices? › Custom Aurelia 2 Project
✔ What kind of Aurelia 2 project? › Application
✔ What Aurelia 2 release would you like to use? › Latest
✔ Which bundler would you like to use? › Parcel
✔ What transpiler would you like to use? › Babel
✔ Do you want to use Shadow DOM or CSS Module? › Use Shadow DOM
✔ What CSS preprocessor to use? › Plain CSS
✔ What unit testing framework to use? › Jasmine
✔ Do you want to setup e2e test? › No
✔ What kind of sample code do you want in this project? › Bare minimum
[makes] Project test has been created.
✔ Do you want to install npm dependencies now? › Yes, use yarn (node-modules)
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @aurelia/parcel-transformer@npm:2.0.0-beta.8, @aurelia/router@npm:2.0.0-beta.8, @aurelia/testing@npm:2.0.0-beta.8, @babel/core@npm:7.23.5, @babel/eslint-parser@npm:7.23.3, and 745 more.
➤ YN0000: └ Completed in 13s 588ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 713 packages were added to the project (+ 406.17 MiB).
➤ YN0000: └ Completed in 1m 58s
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:16.2.8 must be built because it never has been before or the last one failed
➤ YN0007: │ msgpackr-extract@npm:3.0.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.3.100 [95076] must be built because it never has been before or the last one failed
➤ YN0007: │ lmdb@npm:2.8.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 21s 985ms
➤ YN0000: · Done in 2m 34s

Next time, you can try to create similar project in silent mode:
 npx makes aurelia new-project-name -s parcel,shadow-dom,jasmine 

Get Started
cd test
yarn start

```
So it works correctly, the refresh in browser happens as expected. which means I'll close this issue now.
