### ISSUE TITLE
Router-lite - "." in url causes issues

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#2049]
This might not be an issue at all, but would appreciate some feedback.

I have set up my route like this:

```
{
  path: 'entity/*uri',
  component: () => ...
  title: 'entity',
}
```
Using a wildcard parameter I would like to extract everything after `entity/` for my usecase. I will do this in `canLoad` or `loading`. E.g.

```
canLoad(params) {
    this.uri = params.uri

   ... // do something here

    return true
}
```

Works well on on routes like this: `/entity/this/is/a`

However, if the route is something like this: `/entity/this/is/a.test.ok`

Then an error is thrown. Am. I just doing something that is not suppose to work, or is this a bug?

```
AUR3501: Unexpected '.test.ok at index 28 of '/entity/this/is/a.test.ok'
    at ParserState._ensureDone (webpack-internal:///./node_modules/@aurelia/router-lite/dist/esm/index.dev.mjs:1115:19)
    at RouteExpression._$parse (webpack-internal:///./node_modules/@aurelia/router-lite/dist/esm/index.dev.mjs:1185:15)
    at RouteExpression.parse (webpack-internal:///./node_modules/@aurelia/router-lite/dist/esm/index.dev.mjs:1158:53)
    at ViewportInstructionTree.create (webpack-internal:///./node_modules/@aurelia/router-lite/dist/esm/index.dev.mjs:3852:42)
    at eval (webpack-internal:///./node_modules/@aurelia/router-lite/dist/esm/index.dev.mjs:3071:62)
    at Task.run (webpack-internal:///./node_modules/@aurelia/platform/dist/esm/index.dev.mjs:440:19)
    at TaskQueue.flush (webpack-internal:///./node_modules/@aurelia/platform/dist/esm/index.dev.mjs:154:50)
    at BrowserPlatform.flushMacroTask (webpack-internal:///./node_modules/@aurelia/platform/dist/esm/index.dev.mjs:66:28)
```

I am using 

```
"@aurelia/router-lite": "2.0.0-beta.21",
"aurelia": "2.0.0-beta.21",
```

Thanks

**Comment by Sayan751** [comment]
@ivanbacher The "." is a reserved character, and hence cannot be used in a path. The obvious reasoning is that the "." has a special place for domain name and file name, hence seeing that as a part of the routing path, seems a bit odd. Moreover, note that the routing syntax allows usage of `../` to refer to the parent routing context. IMO for those reasons, we should let that be reserved. Can your problem be worked around using query-string?

**Comment by ivanbacher** [comment]
Thanks for the reply @Sayan751. I understand that seeing `.` as part of the routing path seems a bit odd and it's probably only an edge case. I can definitely use a query string for this, no problem.

Now just to play devils advocate, should `.` really be a reserved character?  Does this just add more complexity to the router that could be avoided?

I am not to familiar with the standards here, but I thought that the path component of a URL can contain any combination of valid characters, including periods. 

Why should the router care if I name my path: 'this.is.a.path' so the url will be `<base>/#/this.is.a.path`. This might look odd to us, but from the routers perspective it's just a string.
