### ISSUE TITLE
Conflicting reflect.metadata trying to debug the gulpfile with vscode

### ISSUE THREAD

**Issue by DarkHarlock** [aurelia/aurelia#932]
# 🐛 Bug Report

Starting a dubug session with vscode I get

```
Error: Conflicting reflect.metadata polyfill found. If you have 'reflect-metadata' or any other reflect polyfill imported, please remove it, if not (or if you must use a specific polyfill) please file an issue at https://github.com/aurelia/aurelia/issues so that we can look into compatibility options for this scenario. Implementation summary:

metadata:
function(e,t){return function(n,r){if(!k(n))throw new TypeError;if(!v(r)&&!function(e){switch(w(e)){...

decorate:
function(e,t,n,r){if(v(n)){if(!M(e))throw new TypeError;if(!E(t))throw new TypeError;return function...

defineMetadata:
function(e,t,n,r){if(!k(n))throw new TypeError;return v(r)||(r=P(r)),g(e,t,n,r)}...

hasMetadata:
function(e,t,n){if(!k(t))throw new TypeError;return v(n)||(n=P(n)),function e(t,n,r){if(m(t,n,r))ret...

hasOwnMetadata:
function(e,t,n){if(!k(t))throw new TypeError;return v(n)||(n=P(n)),m(e,t,n)}...

getMetadata:
function(e,t,n){if(!k(t))throw new TypeError;return v(n)||(n=P(n)),function e(t,n,r){if(m(t,n,r))ret...

getOwnMetadata:
function(e,t,n){if(!k(t))throw new TypeError;return v(n)||(n=P(n)),y(e,t,n)}...

getMetadataKeys:
function(e,t){if(!k(e))throw new TypeError;return v(t)||(t=P(t)),function e(t,n){var r=b(t,n),i=x(t)...

getOwnMetadataKeys:
function(e,t){if(!k(e))throw new TypeError;return v(t)||(t=P(t)),b(e,t)}...

deleteMetadata:
function(e,t,n){if(!k(t))throw new TypeError;v(n)||(n=P(n));var r=h(t,n,!1);if(v(r))return!1;if(!r.d...
    at Object.applyMetadataPolyfill (D:\slim_redeem\New folder\test1\node_modules\@aurelia\metadata\dist\umd\index.js:541:23)
    at D:\slim_redeem\New folder\test1\node_modules\@aurelia\kernel\dist\umd\di.js:13:16
    at D:\slim_redeem\New folder\test1\node_modules\@aurelia\kernel\dist\umd\di.js:3:17
    at Object.<anonymous> (D:\slim_redeem\New folder\test1\node_modules\@aurelia\kernel\dist\umd\di.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17) {stack: 'Error: Conflicting reflect.metadata polyfill …quire (internal/modules/cjs/loader.js:636:17)', message: 'Conflicting reflect.metadata polyfill found.…;var r=h(t,n,!1);if(v(r))return!1;if(!r.d...'}
```

This does not happen if I run the task without the debugger

## 💻 Code Sample

- Create a simple test project with `npx makes aurelia new-project-name -s dumber,typescript,shadow-dom,sass,app-with-router`
- add the following `launch.json` in the `.vscode` folder
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceRoot}/node_modules/gulp/bin/gulp.js",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```
- press `debug` button or `F5`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.8.0-dev.202007050834 and 0.7.0
| Language         | typescript
| Bundler          | dumber

**Comment by fkleuver** [comment]
This can be solved by calling `applyMetadataPolyfill(Reflect, false, true);` as the first line of the entry file you're running
